### ISSUE TITLE
Adaption to NeuS?

### ISSUE THREAD

**Issue by xucao-42** [facebookresearch/lightplane#3]
Dear authors, 

Thanks for open-sourcing this great work!

I wonder whether this memory-efficient framework can be adapted to NeuS-like framework.
Specifically, NeuS training requires computing the gradients of an SDF MLP, which are used in Eikonal loss and input to a color MLP. Will this gradient calculation pose a challenge to LightPlane?

Best regards.

**Comment by davnov134** [comment]
Hi, thank you. We have an internal Lightplane VolSDF implementation. We plan to clean-up and push this into the public repository within the next few months.

**Comment by xucao-42** [comment]
Looking forward to your implementation!
